#----------------------------------------------------------------------
# This file was generated by ./build.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
index = []

add = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAXCAQAAAC7KEemAAAABGdBTUEAALGPC/xhBQAAACBj"
    "SFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QAAKqNIzIA"
    "AAAJcEhZcwAAASwAAAEsAHOI6VIAAAAHdElNRQffCAIWLgShBJXnAAACAUlEQVQ4y4XTW2jO"
    "cRzH8dfzPP+NDXuwIYeM1ZyK5IqGQnO6ICUiknJIKxdcyIUbpXaBcqHkEFK4kVZmuXBhcyiH"
    "myljxRw2skxTNuaZ5+fi2exk87n7/vp+fu/v9/v7/mLuKvR/xTyy2w8iRaZp0TlkekKBJnGI"
    "BF9t8ToT/lNpha53B5GYTg3eDElIS/UYII6EtCDxj/Tf4mJ9Db+tVOasx8oVCP3aPed5T5gx"
    "BFOUqlJriSnS/Rq+o7a/IeGmZ5p8s172AMIHyYGEPEW+a1MoZ4ChVWfPWdQ1hdXO2K/CeZN7"
    "NZsxVHggR8iUGtMgV4nRNrjlhT2SXbdlW2NuL9Irm9R2E2JqvdWmwwVxBHG7TfdTtSeazVBi"
    "vqv2qaHBZ0U2q7fNRPfUe6lOnV/e2yHXOMVGmOSElGdmxv/W+0saKR06ZJkl5ZDL2h1UbZGP"
    "DrtogQMZQrEs+YaLG22spJ2CG7LBacFaMFujb1EXIaUFtIKpeCDfXsMtxE5LvXHdSysixIw0"
    "ote2puXjk4kOGAU2osY1zZkpFbjkR896CQpRrNJ2WXZZpdxTXyRMJfIWyd6Pj5RgmVMqsBzV"
    "qlBijk+RrSJ9FQxz0jplyqW99lArxjlijGODfZmF3ml3XJE8eZIWqxLcNsGgKlUnaFDlivu+"
    "CioVG1LzXNAmCIJGR42HP2hMn/L4teDJAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDE2LTA5LTE3"
    "VDE1OjIxOjQ2KzA4OjAwuTQ4EQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxNS0wOC0wMlQyMjo0"
    "NjowNCswODowMMOiVooAAABNdEVYdHNvZnR3YXJlAEltYWdlTWFnaWNrIDcuMC4xLTYgUTE2"
    "IHg4Nl82NCAyMDE2LTA5LTE3IGh0dHA6Ly93d3cuaW1hZ2VtYWdpY2sub3Jn3dmlTgAAABh0"
    "RVh0VGh1bWI6OkRvY3VtZW50OjpQYWdlcwAxp/+7LwAAABh0RVh0VGh1bWI6OkltYWdlOjpI"
    "ZWlnaHQAMTEz/4PLywAAABd0RVh0VGh1bWI6OkltYWdlOjpXaWR0aAAxMTdrH1+PAAAAGXRF"
    "WHRUaHVtYjo6TWltZXR5cGUAaW1hZ2UvcG5nP7JWTgAAABd0RVh0VGh1bWI6Ok1UaW1lADE0"
    "Mzg1MjY3NjTKh/Z0AAAAEnRFWHRUaHVtYjo6U2l6ZQAxLjUxS0LpJMHiAAAAX3RFWHRUaHVt"
    "Yjo6VVJJAGZpbGU6Ly8vaG9tZS93d3dyb290L3NpdGUvd3d3LmVhc3lpY29uLm5ldC9jZG4t"
    "aW1nLmVhc3lpY29uLmNuL3NyYy8xMTkwNy8xMTkwNzE2LnBuZ+zxjMYAAAAASUVORK5CYII=")
index.append('add')
catalog['add'] = add

#----------------------------------------------------------------------
addimg = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAKSElEQVR42t2aa3AT1xXHz5Vk"
    "WzK2sQ3ODNjg2IB5E0ja8kim6xRKwtu82obJkACG8iqBElqaTgemX/slnabtlKQ0KQ0QUifG"
    "lBgbqC55MOZpilKeNo8A4Y2xJVmyrN3bs3d3pd21ZFtT9GHtnfXefUja/++ce+65Z5dAkv9+"
    "d2Rz5vnbZ3/7VFa/sYQQYLgA/48LYxBdJPWYBN5AS7A15H9v5yJakez7I8n+gTcqX9m/evLm"
    "6Q67AyXiwsQYW1yZZNgeb/yS1V34vGzXoiNVlgXwq+ryknGFEy4++/QEENvQwiIDEQXLVhZV"
    "AAy3/BhEj0mpYZAcIvzt8DufvT+/ZoZlAWw5uEYYW/g9OjxvLEhtKFFSLc5MlpchgO6cDKZ3"
    "CCq+2kH/OOuTFy0LYOvhtcKogmfp8D4IICRFhUdWyShcFc/3s9qhsm4n/ZOVAWw5tFoYOWAc"
    "HZbzDIghnbvzLiCZYoGknlO8gSGAqrrd9M+zK60L4DeHVgojC56hJTljsAtIhkAnMqN4ydAF"
    "RA5g37E99C+zq6wL4NcHVwgjCsYggNERACKTTBHfKFwPYP+xCrptzj7rAnjrYLkwrGA0Lcke"
    "BWKQGcXqrR9raOzdDtXHP6XvzdlvXQCba5cigFF0cO+ROAyyyPDHTMKjx4wAak7spX+dU21d"
    "AL+ofV0YWjCSDs4aYfSATiyv5QMsux0OHv8X3V52wLoANtUuFkryR9DirOEgyQBi9f1OABw6"
    "8Rl9v6zWugA21rwqDCkYToszh0UBGCK/GBeEhADcJw/QD8oOWRfAhppFwpD8YbQocyiIARbp"
    "+6I+2puiv6QtmAnSk7V0x9x/WxfA+pqfCIPyh9KijBIOwBwDmJYTgM71dQA+P3WY/mOu27oA"
    "1h34EQIooYW9SrALSEbXj2V5FvUAlh2CL0+56Ydzj1gXwNoDC4Ti/CG0MH2wLgh2D4CEAI6e"
    "OkJ3zfvCugDWVM8TivIH04EIQFQBKG6vE6rNCsE0QiCAutNf0N3zvrIugFXVZQhgEB3gGsQB"
    "MJPwjn3fGASP1R+le+YdtS6AldWzhcL+xQigOOIBUUuLRsGmfbkecKK+jn48v866AFZUz0QA"
    "RTTfWWRMhPSuDrFAKEHwZP1xWjH/uHUBLNs/TSjMRwCup0EKAIoLR4UarK4DoLXRA+rrT9JP"
    "Fpy0LoDXqqYIRQMG0f6uQgSg5QFRq4tqIiQSLSEyAjhTf5pWLjydfABvHS63+YLe7zhTXS6b"
    "zQZ4N1qRmt8Yi9XmBU1zSTu6HwqHINgWHDukuOTtfs6BkUSIC4awUayhrQbELPSA06fOuDLS"
    "14fag2Cz2zBYhiGIrhSUWiEg+SEktfFPdFDE1DbTr3hCvjSM23Zy07M80Mgv31C9KPd+093a"
    "SSNefM6R4oikq4atKl5pxTmuO88Yi7Rzc/qAo9WJMQB07t5JDNDaCKDZ2wRtobZIdqj8BoMH"
    "7bfhVtvVrs0rC5dU4ZLaFvFwi53BQ8c2z0bfSvLKztLfL5u6bp3NTnjltuO83TxR0Y3XLMb4"
    "bU5y5Gt4/zcLlZdOPMGulMYNOQIuD9ruwHn/aTSopLgv0a2RfaajQLhHK0AIsCDuh3B7LwWg"
    "xT6PrNpX5l7wwuJSuW4vNdmMFZvOSlcxoDB9Xm/a13+PckzUnZNMQnElou5a5cyD0B244D2j"
    "iNdE21gUgE0Vr7X1+0TH4oEdmN8OcDtlKwdQ9vyiUsmHVvJCtFytr9zESl1ZVKRBQAevEGNY"
    "uasYoMCJ7BPZ8nfhou8//5f4SM94iACaEcA9BLCyao579vM/LuXivRCdqkae3JisaZ7OGiK7"
    "CUCs7gFiHCi6c8R47GHoHlzynX0i4jmA+wjgsQM9wbGVrKia5Z41aSEHIGoekECfZyB2DSCu"
    "5eMAkLESpf0odP+JiucA7mKwf4we8BABLK+a4Z4xcX6p6NV1AU14zAeZRvfWFzkifR9Mc3v9"
    "uB+RqI8B0T4fjRIiNIcfwSXvWX7uSYnnAO4ggCYE8AgBlO+d7p42qaxUbEHxLaDcXMTdzV7Q"
    "MWXt2vJiHEt3vFa2sqieb25/CJd9Xz9x8RzAtwjgEXaBx/atZOnel90vTZxdysW3ENPjak1s"
    "WLWq5vZhU7/uCoTq1uYYQGKAIbL4R9Dg+29SxHMAN1MQAHpAMwJYsneq+4cTZqoeQDr2fdMw"
    "2GH46rblO4kBJHq97PYNvnPoDckRzwF8k6J4QAsCeG3vFPeU8dNjAIiRselLVvqhkET7vDZ8"
    "sRhuH4kBxBQfiOb2TdDoP59U8RzAtVQ+FIIfASyunOz+wfiXFADNJGrdWJ4Qa9883JHOPEG3"
    "JcZzPrE56ZaPALgiA0APaLVtJa9+WuounTC1VGrGGIAAzEKjJSxdHzYHQxKrKxitGxVsBiGC"
    "L9wCV/wXsB1OungOoEEFEEAAC/dMrJnywrSpUhhv5y6mwqIUA4AuhWUmgWbhJI7lSTzLt8BV"
    "Lj75lufiAzgPOOcCaCPyupnM/PuYJc+NHb89L/cp5RWWkL5+HyMZipf4xEuG8DvlHCMy71ch"
    "yYsfT1zzX4wtPoUpq/anzea0mZ08sTEfi7TjHJNngl67MiUOEC/+zgjOb/K7Q7bkZvd90+V0"
    "ZXR4dU2/b6gHaPN/cy3A+LmcpzMhjfVS3hHSugSu/rAPrrdeim95F37HPYeSs2vzeaaJ1+3r"
    "5/rm+X+860VSj1602rPJV5fUitDLlSVCaq6d5qTnRQHg2oop5/XWhs7d3omecs4JnteDSb3H"
    "pH556UcDhYx+Lprt6qO8IYKCA2IrfBNs4FWhTvt8KlMALLEygIoBQnrfNNo7PYd7QEBqhRvB"
    "xq7Fy207AjjvAs/SgHUBfP+f/YX0PCfNcvWGQDAAN4NXuydebmNTuoAesMzCACZ+nCdk5qXT"
    "VGca3Gy+ntg4344ALiKAcgsD+O6ebCGtr4P6bc38PcGExnns+tIlBLDcwgDGfdRLEHOCFFJR"
    "fLstsSTHj0nZ5TTwrLAwgNG70wSSG6YkDQdjGUACGR5rsWHKih7w01YrA0hFACIlOKbz7CuR"
    "6m2THVgjesDKngDApQPQzdyeyaXrqwhgVU8AkK4CSKR0LafBOG/3rO4JAHpJcv6dWOlaLlxe"
    "Rw9Y4+8hACRIrHR9CwHcQABrewKADFGZjiZSur6RAuwmdoGf9QQAmaIyHU2kdH0dAdxCAOus"
    "DGCXCiALARDSbfEcwNVUYN+mgOcNKwPYiYlQDgLIFo1JUHdK140I4DYCWG9lAB8igGwEkBMG"
    "cHRfPAeAaTC7gwA2+CwMYIcKoA8CSEns19iFNP4Sg+fnVgbwgQxAoqQvAkhjCX1W+topP70F"
    "z0YrA9ju5DEA5FEgE2eE9u59jj+/v5bGZ4SeN60MYJtrMGRIl3kMkHRVWrVEbdjKxzFbZCJR"
    "avby1m+74vmld5BlAXAIb/d6F/q1l4OTAVFFGsSLJvHaq2xB0oatMs8m3wFLA+AQ/pA+F39q"
    "DM8DmDbdg441/OgaxDurQPdvSPa9/Q996Z4wOYvlNQAAAABJRU5ErkJggg==")
index.append('addimg')
catalog['addimg'] = addimg

#----------------------------------------------------------------------
addimg2 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAADFElEQVR42n1TXUgUURT+7uy4"
    "P7PurutP9qMllLkU1EP0B6aUFQVpSogFYan1EASBhfTUD71EgQUZFaTRz0Plg67RSyhiGhZW"
    "kOGmmeSqK+7supu7OuPOzM50nUqWgg4c+O4953z33HO/S/Cv7bClM9Wu7UzBGpe6khANI4OG"
    "MU+v+joaUJtovDsxmSTgNHMGe3/TMfvBfeUqyVkRQ7JFhRwnCEaSMOE3osetaX0PIm1iQKmh"
    "+dOJBEu4NVzXgUsOV/meEJI5FYLEUDckOINwlEV/vwlvrk8PzQ0LBbSO1wkM6ab2I7edRTUl"
    "AYgyg2l64qxggEJPVzVQJxDidH/eiNl5AyUxo++yryMeiO1eIDi45fzS1qsXA3rQ6zdDUghY"
    "wqFs1TO9vRZvBRRNQIySjIQ4hEUW79oA311vKSFpZnfje0NJZqqELz4rYrSDBVtq2YDq3E4d"
    "Nw3vxJTYr+OYwuCjzwY+nIS+2jE3ydvP8Tefyxnfg2ZMhk2LE13ObcCpvA4d3xkqwqTQvxgb"
    "nTZjiLdi4FaAJ8VnjOrxC4R8GLfDhBXYu7wWRsYCjnXC5SjSCwZnOiAoYUiqiFeT9fBFebz5"
    "loLJ5qBKDp1j1dKzRtL9PQUHss6iOLsW/7MX4/Vo9d5Ap8eJoJvXyM5K1n/4imVJt9eJFCYH"
    "FVl1MBloB0k2rM/crBcN+PsgyFE6RBHPJq5hYn4cvV8c+PF0IkCWrWXcdS/tJR/9dviF3zOg"
    "T5drX4+GbS368vTbMgxHBhZVE46wGPJaEL3madOf8cRDe6t1HYdePhWa9ivJ5ViHR/nNOq7s"
    "Kadz8PzhhnfUhPBnEcq9wdIFApKx2tBe0ZS2yyslwxO164n0EniytUnHR99VQ4Sg42iQIDTF"
    "QGnwtIMX9/yRcmbWZlNX/oX0PJ4WfhVsmFVZKL9qwHIAo2iIz6iYC2pQHn8bxEikcFHKvy3d"
    "uoxtdFWlFSdvtJGQbMSMnKQLJy4Bkkjl/CmiKS/HWxGKnfz7MyVaoTGVreJc1gLiNGbLVL5S"
    "QBqTh2e7tIi8cKeexOSf7+dVsmfzC2sAAAAASUVORK5CYII=")
index.append('addimg2')
catalog['addimg2'] = addimg2

#----------------------------------------------------------------------
bundle = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAGhUlEQVRIS7VWa1BTZxr+cm45"
    "uQAnJIRAFKJBIqJctNgWlEYoEFwR7Dqtne1Y7JTebLvO/rB2tzNtZ9pu2x9dx2m3O9pZaG1H"
    "67itNFQR1KaKtCIqoFwllHBLCAkJ5HJOTs5l52MnFivuv55f53vf93ue9/ne9z3fkYDf+ZH8"
    "P/wf6s3Ulj02fyym5XBZHs+j/soXm0djtt/G/BbvHgIIUv5caxcMPHvE8lZFXfNbvxJYaiUS"
    "MFpW12yL2RbHLN4b899DcPaIpYHAmH0w8wsNVSf5aPTjGKDt6I6PeI5jS/dYD0CA1iMWM4rj"
    "L5fUWndCJSxHHqyoa65drEICHRwnrS2rO3sQOmyfV/+bFwQ3BGk7/vi/oixt2rLbumXB90XN"
    "JZQgejbvOrEXrn88Wt2G4tJbm3adeOF8fdX7KIJozU83PvM/8op9GBZpWFAAFxIJWvfos6ez"
    "oWQUQV5DkXAKy5H7JAC8iWOMCiq6+OWOAUEQWPPuxhyYWJQjfSIAbxMYc5AXFC5R4A7ARFs/"
    "q+wDonAYvi8QwGCel7ukJPkfhg4fIUhZC8uE9wtAQpEy2RsME9pZ8WzLqXOfbWUIkhwrfuqb"
    "zJbDlloMx+qjHPe2FMcivADeEXiuFJeSf+FYthxFwzqY1J0awPNGUWw7BKY0yW8E5/xhlmNe"
    "TVTrvg0F5q3m3ae2Xz72+FQkQstKaq0q2xc13yni4qtmva4dBEYeUiZQcp/beUAqV/6T57nv"
    "YF1g8ncIYMHiKXVTOBSYJeUKOYJKwn6vZ78xO/fYxPDQlPnpRn3710+4RUHkip48kXqhYdts"
    "2qoslb23+0mVJvkfPMfhTDgUjlOpEmanpx6JdeJdXWQ7WuOi1En4nMcTSc80UUM9Nw4ZTNkv"
    "eJyTTCgwt4vSaE9y0ShgQs4MqSx5QK1LAY6h/obMnPV//mWwN6TSJCOzM05QUtuUuGSbXvzq"
    "j82phpUVE8OD7PrNpUTnj+fbU9INeoHj5FMO+3tpmWv+6nNPSwN+75up6ca/IRgWcjpGJ/MK"
    "iwtvXrkc1Rsz8An77YXjXJIAFi77gYfqh27d4M3bdqIXGr92p6avpOUKZfpgz7VPDKa1taIg"
    "MI7bfcdNORv2hkNBx5RjRFZS/YTW1nSSz1ybj/Z2/ryn/LnmhiUJYB10aYYvZz1uXXHlDvTS"
    "9994ZMo4iXFNjrqno82qNxgtoigyU44RW87GTVVD3dfm2AgT3fyHxzTtLVYuXpU47RobfWrx"
    "pN9Vg0/2F2elGdTXpCRJxKlU6IxzipYAgCw3ZkqH+3rmNbrUeFEUOe+0y5exZl3SuH0ogiAI"
    "F5+oVtDBIM/QNDPhmNvw0oc/DC6p4NDrpWuW6eSXKE2iCsMISZSN0MHAPGrMWkcMdHWG9CuM"
    "CiYUFD3TrnBWfoHC3n+TVcbF8zghlfECB3xuz+ykK1D0yt9tA0sSfPz6lq1xSulJUiaTSRAE"
    "ACCCCE3zlDoJ9bpdQjylQnieB6HAnKjWpkh8nhmBlMsQ2O2iIACGpulgIPrY3vfPNy9J8OkB"
    "syEtPeFKYrJWC9uRUmvBxMhtbnV+AXaz43JkhSlbCjeODvWG1xYUyQe7Ojn9igzM73UDDMfB"
    "jNPpd44xuc9/cG7sPgpKH9Ymka2KuAQFgiCAkJLA53HzKWkGdPIXO6tOTiHgRs/0ZHTZilW4"
    "c2yUV2m0KMOEoVgQmp8PeGfDj7747oWO+7RpWV5KurEJAKCKp9TyOEoFBruuCQ+VbUXaW6xs"
    "Vv7GBYK+61fYoortBOycdRuLMN+MG8z7vWEAgM/psG+LTfFdnwq4gHNgyl1fPz4yHDLl5Cs0"
    "KctAe7M1Wmipwn9qbWJX5xUsEPTf6GALy6uItjON0U2V1bjHOQFu3+qi9QajbLD7+v3noO3Y"
    "zusPlljyL54+xeQXmklVUjKIgSwmGOi6yj5ctu0OgXtqHNy62s4Ub60hfzr3fUfxn7598J4j"
    "OvOpxaDRaTvTVq1W915t7zLlPpCXajDeIfj5/GnGlLOBhBuH+7pDBY+UKy6faYwWVVbj9v4e"
    "2Aw3czZuWmfv7/F4nO6C2L1919dUKpd9wNKRXF4UjieoEqspdZJ/0jGyXJ++cnzGNalRKhNY"
    "SBAMzhFJOr1ncnRkud6wctzvnaH8Ps9ZDMFrCJLojoTp12LTfM+dDC8fhiEpDAMGCCYKfIYE"
    "QYcFUdChAAShjQdAiUgQV8wHbRwHRkmS8S/+C4H2/wJARDf0PeQ+pgAAAABJRU5ErkJggg==")
index.append('bundle')
catalog['bundle'] = bundle

#----------------------------------------------------------------------
close = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAD7ElEQVR42u2Vb0wbZRzHf8+1"
    "veu1tDdWaLu5MaTZHMgLxfiiGY5lJuxPYtyLsTiSqWDM9kL3Zsa9mDJm4mKiLDEumYlC14LV"
    "ORnEKWXaJTSLM+7EisyNyCkU4v4Box2F/r+fT1t62mUwJfGFiZfcPb/fc/d8P8+/73ME/uWL"
    "/A/4bwL27d1rWV2yeq1GrQakGhMTExCNRIGQtBxCMBQS29s7oksCvNDYWFJdveEnjuOMC33j"
    "8fSua+/okPIArxw4sIFRMfyi6rS7PK+1V1RUvJHNlPZ5cU+PZ63T5fo1D+Boa5UMBoPtXg3u"
    "GmkuXxjg8axra3Pkj8DlPCmZTKYy64oVgIiAMmZKGeVsPl+n5PPv/TcjEEU1gEoFJToZijUy"
    "DA8PvyvL8pWX9+//QAF81NEulZY+aHu4shLkVApTskxoCan8GGiMNCa5+re+nYSbshYZjic7"
    "VqbgkYIoUnEyPj7++e76+qcVwCcfu6Xy8oqyNaWlIGeFMoL3iv8Cg2M/hmGKFIBg0MNmIQwP"
    "aWaAYRiggLfrdu06qABOf3pKerSqylZUVPy3RjASGMPffr9FrgqVsDJ6DWd0ZlJp0cP0VRFX"
    "mU3k9uStxoaGBocC6Oz8TLLb7TadTn9fwMhogDSfDyDtOdnM34DGrXacDoaI70oAvk6UoBFi"
    "xDz05fPu1vedCqC7u0uqqdlkS5tlMQAVxybvCAkwxahhWVKoTkKDdRrVDCEnJ80Q0RaiSq0m"
    "hTNjs/HzH+5QAB5Pj1Rd/UTZQvOei73fiHBsiIE49Rn1BHCsBgQmARoVgaDKAEgYAEYFPMSB"
    "8x4/qgB8vj6pquox27zQwlNE83MXvyeu6wLKvEA4jgVeq0WWYwmhwnPxJKqSUWC8J1quD/lf"
    "VQCieElav778/gC6BrQkPnEAO0MWohGKQMtxmWlJe0GOzKDxkrvLf8G70y9+hwrg8uCgRLdo"
    "2WJbU6bGyjSg63SxfwA6by8HRrAAq1EDBVCz0XsuCKSvtdV5vOXFPCdT90lWqzV/BFQY09sS"
    "sx3JOljGC6KfuG8YkBHMxKDLrAMyKhWhD4gkqMUjd2Di1NHXvzrtevPPs8jhqGNZ1pgRzR0N"
    "d92xWAyuTYWeFYXHNyZ1y9Go54lQwIORSSBdY5hljSSSRIwjQ9SxGZxyHzn0j4/rjU9uqV22"
    "bV9XxGTj9VoNmFgZps++1xKbmw2v2dN0OMwtgwQwwE6NxgPO5meW9MOpqd2+xfLUS2eI6QE+"
    "eu7EO6OD/QcHfhBxW92eplXPHWnG2WB82HF4t6/3bNeSf5mbarfXGkyWmrFfLr820C9irn7r"
    "zvpD0fCdn/t6v+hO538AsB28+8CcmNwAAAAASUVORK5CYII=")
index.append('close')
catalog['close'] = close

#----------------------------------------------------------------------
curriculum = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAC6UlEQVRIS92TaUhUYRSG33un"
    "WRxzTGYoFwIbLDSTyT9pKGmWEAOKW4kKSYghphS2KG5pVqa0jFBmZbiUKSiluBemYmbZgoOE"
    "IqaG0bi00JhljHNv3BtOjjM2GvqnAx/3xznv+5z7ne8QWOUgFvoHJDXaU4TWCwRhz+Rommir"
    "zZa3/2sfOkBARus6kpq5OjtLRdhKzL9bmvP4FEVrRlRTHACfZzRUTG22vHq5IBbAdM0TEN3O"
    "9mJRjL8zf72VGeszMDjEfkfVPNyoeaPhcTmKsjTfU8uBsICQ9MZ+j202m4/tl5HzxZkXFGh/"
    "8gyP6yowpFIjqaBT6zDVVen481W/KQhFUe2HCpraiKD0xiiRkHe9KNGHO1809W0ae/3CEBrs"
    "h4S4aDbV8vo9iqtfwPdToSl/Jp8Zmd+QQURkPew5sNtB5u+xSU9U19SCrJw83LmlwBYHqS4X"
    "ltmMczvGIBXNLgopvXf/D8A/uZ4+G+UGF6lYJxh+N4qIqHhYrDVHc3WZnlFiQQcE1Ftst5sw"
    "ADgKzeAkFMIk4PnLHsSfTINAIEB9ZTELmoukm08xrFZCYDViAAiQiBEoEesDgtMbVSdCXa3d"
    "t27QCWiaRmFpBQqLy+Hl6YbcrBRd7vDlR1CTveBbjC8NEJTacHeXzDb8aIjMYOnKq2qguHYb"
    "uVnJ8PJ0x8SXH4i+2ApL+04QpOEMjP4Bu7kkNXwlzhNSG5FBV8wzZcyZOFPajYGJAXCseo0O"
    "2CiAqQxKbTjO5ZI556N3coxBmJq8KiU6+0YhsO4y2j1TsyiASQam1CdoaVzycbWDu7M1hPw1"
    "IAgCwyo1HnQMYlqjBk+iBMmdWfR5/hXAqPKPhNJfN+7BoNYOk9O/fYQiNWj+B6NDXUgyCSiJ"
    "ldMyFycwJ7J/YCnbqlfzHwNKYuUZAE4v+06WIGCXaw7A3P1Kxdj4JMYnPkIPcDA8aKX8oezt"
    "Y48eYMXc5xmxgKKYfd4kSXqvGmA1jOc8fwF3y0ZNlQWNQgAAAABJRU5ErkJggg==")
index.append('curriculum')
catalog['curriculum'] = curriculum

#----------------------------------------------------------------------
delimg2 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACPElEQVR42o2TS0iUYRSGn8/L"
    "jKYpqHklgzCLUKlNLUIFq1WkLoLaWNhlE0EQtmtRUEQt2hStypApqE2MQtTCArMgIpK0UIuK"
    "hkFy0rJk7pev97ekqUw7cPj+83POe27vMfwtjaWwfws01UK11Y834HsMDwPQLXMw3dmkfReX"
    "w5XD0LZrOaakEFzZkEhBMAJfZqEvhL2s5yMckP90OkBpHQycL2Dd5tXgzoFYEuLJ399QCN5N"
    "wskI4y9VoeICcwCV0N9TxtbGGmVMCFVOmcLPDIPTQswFM/nylkYF9H4KuoLcn4BtDkDbuQK8"
    "R+shqYCMUWmYBSWslsaKYVZRDwRyNk67qYDeZxtoLVQWOyyvCItKJBOeFwkkDkdm6DXt+QSu"
    "17Ei5heAn/+SD7nw1g2XZjWDY2WkTlRjopqKu2UHuR0dGoJZONJawh4Pn+/e4Wke3IqSMscr"
    "SXWVY8JDUPFiGFd9/aLZYyMj+BsaGFwGt2NYs7eEyTNVlIZeaYi795C3r1MFmH8UYAn2XCN5"
    "4yZP1IInzidT66b33hpaQz4BfNMal+g/SzqVoW1ITyfom1ujZxXeBi084lt6gA4vRp1NiKEX"
    "rdbosLHGJSJV0YIqiE8vDjChzH6hXLD0i9Lb55st25TDwKki1mY7PBCQSfziuZM1KmPSURnd"
    "lrHX0Mw8lX9KSWUmVw/ms3NjFsaKKI46xxRSUFDvUBLrtXhV5CH+OKZ0aS4ydK7PokmEW5lS"
    "cCCJb9wy8PXHOT9Kd/4OV+3XOOnNbwYAAAAASUVORK5CYII=")
index.append('delimg2')
catalog['delimg2'] = delimg2

#----------------------------------------------------------------------
exercise = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAADKUlEQVRIS61VzU8TQRx9s7u0"
    "XdLypRRRPg3iwW8v6kHUKLR4wqMJxhJpjTFGCFHEKJIGJBACaKJGqkH+AvSgtHgQPZmoCZZE"
    "0fAlIJGClO+20t0x27KmQewCMpdNZn7z3vzeezNLsA6jvcnQCIYUQEQ/IJhyLC87ZVjyv/jt"
    "TUYTCJrjN2+B2zUKwe93Zpvte9aNwGEzVhDg1sHjuej97MTPkRHPCXNb5KoIAhIQcjm029ck"
    "5ZNO8J7fI7qGOQ5dFNAG1im9k2NxFK2YwGEzPiHA2VBwJxLgJAmBqU10pidVcJdlsu4kkdAB"
    "Q2H709DasB4sBz4LFZ4zmdBqo6DlNRhyjWMjnfXWm+/zy/n5T4KlslCgxWC2m87YrnRwDHt4"
    "b2Y6MzU3h57hH8iiA0ih7n2h6VGUqN1mpHKRDJ7/6GoeA7SmJ+qhj43G++4ebBBmkIO+v7RX"
    "Jlg0VgY3NRfFiIKqi9eoEvdv28oOjo4H5DkpfkUc8YJSDBgs9vSlMq34HljulbR61WzejvRk"
    "aFQqfPjSK2G15Isf80BIdCiwREYgnJIkWxHBpeprV3zTCbWcTsT2Q9Hoc41gYnp2luV+JZ/2"
    "dzcuTVkwrijIsdilBIYfpoqGGN7vcwmCOiK4DxB1c4B+ouZxYf21tgfGNJZDB4DUEKRvgh9H"
    "cy/YBxQJbljL3o569AekQk1kJEQq4pfHi6iIqTd11oojSgcMS2C1lhQOe5JswQtKwTAsEtNS"
    "MDb8Hf4FH31YXcKsmaCu7lzq0GRGj0fQcIuaBj5qnkekTgf3mAvx/HhpVXlVbTiSQAeSjgyL"
    "V4QgTS6eW+DRNpT1Z6+eH+v1+fn5qQXtrqjYOMxMuqFmPDN3K8uiFAnkF3Fp4YvBLMz7eUjg"
    "leW3M6T1i9drvAtUpWY5TnqaEcsP7q4pb+j6F8mfDpZJAt6N7YRPYDutN2v2yQCl1uJd7vlk"
    "J0jQPiWzFVO03MkcTYZOQkjwp7KY97AdKCUhdH0x9/3yXATnjT1W0DG5bgQvbYYiCtIQPDx9"
    "ZjA78hRNXk0Hq5FHwl21B6HPuJI8ayKQI01Ai7PNjkal7n8DqMlPKNEOwDkAAAAASUVORK5C"
    "YII=")
index.append('exercise')
catalog['exercise'] = exercise

#----------------------------------------------------------------------
illustration = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAB4ElEQVRIS8WVTUgUYRjHf8+8"
    "6+6Mu+CCH0WR4hZ9eVEQIugUQRfpg0516tShW2c7eFjP3Tp06hSdElGCQKFA8FIUgWEUGxaE"
    "ScoW5kzbzrziTOiMWzu549oDc3rn+f/e//M+7/sITQ5psj57B9C3sOxWhrTQl8SVaOasFsZl"
    "hMqGzqaDH7eZAIaSiIdyH2WLXIkAVocpi9C2GwCt+ZYbJb/dgW5EXNp7UIVB3NJz9PLCpkS2"
    "GFQnXKKGAOaN+xj7juB9eY9z73pjgNIn5ScWDrk1Jq2bD5D2bvTyR+y713YOsG0YmzL9xMvn"
    "HCwryjD2H8PoGcBbeIm3+HbngCczaT4vBQ4OdLmcP+N3X2z80xnMlxSzr9IRsdP9FY4XXKq/"
    "4MOcSW+fQ6qllhcL+L4qjE9nqLrRy55SmotnHRbfmZS/psh3VDk64ITaJYDVBWgNj5+lWVoJ"
    "SrM9etug1d1aO3i4wsYXjrqA1/MpXrz5g28gp6DbNBAJO9O+i3znVpf9FbBSFiaeZvC82ncw"
    "LZqCpVBG7ZpSmpOn1rBywXWKPYPYNon54T8AhnEQMkl37udrfmZH8W9n+C0aAy7tBkDDw1yR"
    "qxHA74FzQQsnkkD8gbPGpNzBjgCSiNbL3buZ3CwH660rohlA6bcLAAAAAElFTkSuQmCC")
index.append('illustration')
catalog['illustration'] = illustration

#----------------------------------------------------------------------
lesson = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAE80lEQVRIiZWUe2gcVRTGf2dm"
    "d2dfSTZJE2PSpBZrSvpSaaPRooJaq7RqQJSKFC0GQUqr4gsUQVDRKqiISP3HV6MIiqCIrVZq"
    "FRStUqPY2libaB9p2cbNO9nMzL3HP3azTZvWx4HL3Jk59/vOfOfMJwIsOSfJkx1L4hVVtVdG"
    "vVQcBOX/hQCKEk4MD+Vyf+18aHOX2d+XJ4JAW0ulePHEa6PD2Vt67YgEqBbPAEzfT7+fkZNE"
    "mBPJ2ETCe2ZZc+ax/X3HiBTYLWNDx1s/SAw5v1Z5KDodUE66gBTwmJHjiHBJ9pBzpV+xTK0V"
    "BI0AGGMl8AN+i0/qof4BmV5i4bTQWNHEvOrz2Nm7A1VFTyOiALWUs9z3MdYC4ABYC6GB/IQv"
    "Gggp0iytu4jq6CzwwQZKfbKBlfNWcXfrRhqSs8EH9fWkZX2YzPsYIxTxpwgUY8AGID7cu/x+"
    "ZqeaePWmNyAUxBfUQG3yLL7v+Y7HrnoCQoGgsDSgsPcLGMYoavWULwgVDVBCiDoejeVNpKNp"
    "JBRsYCGEgbEcfbk+ohJDAiGmHtcvaGdZ/UUQgIaKDQpYRfwTBMYARkVD4ex0PY2ZOaDghA4a"
    "wJH+I/Rke1h/2T08t+1pNFAevPoRKqIZ2hffRKVXXSIpSaQUpshawVhBQpcrmi9nXmY+lckM"
    "6968DT8fAPDnsT94advzKIqogEBjRRNvffUa3X37cEKBAKxCaLXUg0gs5jF3/mJcb4SHVmzQ"
    "tpaVMjw+yKOfPMyPPbtRPTEtU5OjWASHl7e9yH1XP8BwfoSnfn8cGxSkCRWmjkU6Ou5kzV3r"
    "roq6Tk3oePLx7g/Z/OXL9I8dP+M4FsLy84Eu7uvZgGJLgIpiirIDROLxBBEv3TGYPZjetP05"
    "/bL3W7FqzgB6IrT4JTNoBYxMk2j79s9oPbfqjqPfv3fxnvHeJlMCP7VyOc2zU0NQAeNQMptI"
    "9lA3O95/ZXJebWoiGQiiU1rPsCKh+PYMVoQAScfBRjGzKqLSUB3TSMfKBmlbNHvtwGAwuHYy"
    "xU9mjFBPW+m/GqwnwlK3jMpkTBcvOXvd0pbsG3L/DU3xxXNSOVRjRRT5D1hnlKjkhOLYg/2T"
    "tZHRkTDIZsPXEcpKaQKuIImE0+q6nGet5kbHdWvJXwTSabnOEak2hu6JvP5grCo6rTQ1+aGR"
    "YFwaMh7VZbEpXESgrblcLmlJtSTi8jWQAtp3dA1v3bV/DIBFTQlWX5xZBfIB6Gg+z6U/Hhjv"
    "/uKXQdVpJKMT4Um+jwjMrYnzcHtjWcJzvkFoiUbYGovJ846URr3QYkUmfX0wCLkGZU8Q6vIX"
    "Pj48uvfweMmHpnJLURZ3eWB1k9RVRTsdkTWq4Dgzhn36GDnWIgiK6ju5kfD2Zz86qLmx8ASB"
    "4zgAlJeXc/PSCllY7613XV4QcQ9rLHOjcVNj/9RW106kZXLgI1VTb6xu7MkGmzt3DerQ0DCq"
    "imzatImamhrXEaKj+z5vyx/a/QniuOULVtzq1S38SSKe808EGN/mj+69cHjvp2+j1ngN519b"
    "tmDFLsUN+vv7jWzZsqUZWKOq84Pc4QvC8YE6N1UVeFUNgyBxUKfY/1OJioaMVbV5f6Cv0ozl"
    "IpFU5bFYVWMX0K2q70pnZ2dMVWepapWIlANlqhoXkXRRawEyIhLRk3/AEBgEVFVVREaBvKqO"
    "iMgwkAP6/wa9SoBLzqif/wAAAABJRU5ErkJggg==")
index.append('lesson')
catalog['lesson'] = lesson

#----------------------------------------------------------------------
new = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAADbElEQVR42tWVa0gUURTHz7kz"
    "sy9bsShTKSp7KJIUhW2QsKJUtkGZUZRluRFFha4PyA9Fi+2HsvCFtioEQYRUH4L6UqiVUkGB"
    "EKKYRWAPKHts7rqtzexjbnd81E6lweaXDgxz7syd8zv/c+69gzBubXuAcAgCBQgQDrKoDI+A"
    "gp+9wswrEIAIDSecu3shQR8Du0UPXItPFc6/7wmc1kXDGtELzzMvw+OIAW15LHMCcRRBWrhu"
    "9kXvoPQqMWv+zv5bLy/NN821PLv5dgelMOILwNCWayAi4gJK6RL2LZkirpfjuO5QKPQNW/NA"
    "q59JbLErEtO/+r5pVuRmZBKO5+SAFBx40tcvfvI99/mI8U7vnBbnnf4X9gpHg9VqXT1V1i6X"
    "a8Risdh7e3ur8cZOIN18mjU/b61jUdqMOCLokfWBCQJ2D9HBnneeYcx+o0lIHWm5eh1KS0tN"
    "LACyDClTM1pipug33+l0tjocjq14fz+sj06LP5NsXpSqn7dBQCHhJ0D2Uv+He6EvAx99Q96N"
    "nx98iPPvKziQ7PF4UKvVTgqQJAmbmpraKyoqtqDTggbf4pyzlvSo3KSVV+OJRouAUWymBCB7"
    "4HWf+csQ2TfIz1kqPuzqMRQUWJPdbjfodLpJSySKIjQ3N98dBWxLAkPKqsR22zFhDS8YSczc"
    "LiUTqiyAr66l7K6Drq55I8Oz8oOU10N2dnY0AyAD0LBVqPIZ4KeCzUvAuHnXgUc5e48s54bO"
    "IA26ICb2Kf30Nh2NM1+Dm1ygIWkYdbHLgDPEgCzLlBDyV0BjY+MYgD3Vn7Lb7x3K326SX9UD"
    "n7Af+OET4NedZIvtNmD0JjAsSFOvbUSYypQSsSaPlYiN9XYGOHr4oImXReSjZoG7u4Uakxic"
    "bWkqhyjLPDziaEPDG/urAqXJDQ0N7SpAYWGhSaPRjM2Qg4CEj3Tzgt/vh/r6erWCoqIiBfDH"
    "jML88PFvcxRBirJAIIB1dXVqBTab7Z8BE74CqK2tVQOKi4unFVBTU6MGlJSUmARBiLju4RYM"
    "BqG6ulrVg1Z2xqxjgGlTwAAqBbfKysqyJgB/Orx+RB8fTzZH8ZkCrKqqUgPKy8uz2Pk9LSVi"
    "Jy1UVlb+KJHWbDafy8jISJmW6OPW0dHR19nZeXxCuham/kNFYjK7JPznMH+x/x/wHVzcy7me"
    "6PPcAAAAAElFTkSuQmCC")
index.append('new')
catalog['new'] = new

#----------------------------------------------------------------------
open = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAD8UlEQVR42q1Va2gcVRQ+587s"
    "7mRItNskfaY1trRi2sZHNYoQHzGmQkAMlNZK1R+l0R+K/REhRAmzIEElaqX2R/tDhZamov4Q"
    "bV0a6V9Nm9DiI8QEEtpI8zDbPPfh7sw93juzOzv7Ugge2L3nztz7fed859w7CHmGiKocYHVG"
    "wswcvLwFWnNzc3tLS8sjaTIvcX4kBZvD4fBAf3//aeEmShGUd3Z2nu7q6noBHZPABOjA2/9i"
    "js4+wiwrydehUKivp6fnqPCjOQSHPhrTmKI2XP/uA33/k9s6Ot58rSkNnvPzZlKQkTDDMM4X"
    "JXjp08m3aiqV9xUex3sqZqCtqZ6QMSeDdKQeEoISGQiCvo9PfnY0tjBVQNC9d7vf0Fkcq2AK"
    "9jXeR8wrEQB6Ii8gkJWV/skz4ZlLI8posKbOQmQfnnl9y/f2gsMnbnbvuctnaCwOm9QZaH3i"
    "fmAlpCklj7RvLw/Bn8lqSPAy+PVGKnT2ja0hN4MdmxTDDzGs1Wbh+aYHXVm8kebNM5m4En3T"
    "fxXGY1WUBB3HblmGyCBLsLUaDZViuLN8DvY/s9cL+p8SZQi+DF+BkaW1ZKKON/+iLIGUaEMQ"
    "DMZjsHtNBA7ue6hAnlISCfldv++HK/DL7SBwpsP0PGQlOnh8onttBRpgruDD6xbgcGtDTgb5"
    "EkmXc27XVozus7MXr8Lg7BoCtRznlyF0/litgfUdAxcCqnovAK/l3IRKnWBz9Z155ZMZQEHU"
    "cnRcZz41twyROAJj8rZhN5KmOYxtvcMLLz5egxanCimrIiT2qUpBAT1sztzGppw1psXBIlkj"
    "0aQIsYHRSAqffnd4fOeWDRoRXy8iYgGBXab5PKDu1SAxwQXOji5BPGlCirNMB94em5xdxGff"
    "Gx3as23zRotbLoGu+XMzQEgDOagZAqE/SplknUzLwtjfFqDiJ9kTDNn8bxO3JvC53vEfG+o2"
    "1okF68VWTBN4znnaIUpzkJ2JBBZ1BlVVIJlMwUrCBKb43E2MscXBkekhPHBi8qvHdlc3Eqd1"
    "Ygtqoj56ma94Dci5FmT3ZEZRO4jGUwTMZzebXCIlFXkt/Tw8dwlfPjV9qrE+2MYYVckMHAK/"
    "q3uGwBN9uj3JliUaN4UsPoK8QyeT+un3hXPY/nmk59FdFa8GfBSUb/2MQ1lALXrXULYOIMDB"
    "0bz4BzCaoMTgSPQ4Hju31LHrbu0dXaM7ZDmJmxmof29T+wCq6QNCdmtmw0BcXOHJPyaTb2Pv"
    "xciRYGX5J5wsvQRocYLSa5yTbiGPLifasfXAkada2g59kTKpuC6rNJ+C1uULX78iPlxKgHPr"
    "AfGssqiYqzOZRURRlGv/F2BJ+wdsRP1yLA0KOQAAAABJRU5ErkJggg==")
index.append('open')
catalog['open'] = open

#----------------------------------------------------------------------
remove = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAAYCAQAAABdXGW6AAAABGdBTUEAALGPC/xhBQAAACBj"
    "SFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QAAKqNIzIA"
    "AAAJcEhZcwAAAGQAAABkAA+Wxd0AAAAHdElNRQfeBQEVCTKXRLS4AAABg0lEQVQoz33TMU9T"
    "URjG8d89vSAaya3BhMRCKoaIA0wyGDcHZ3VsDAu7H8APQOJiHPwEalzddHWSD6AOhhhLUgcb"
    "W1oL0hbbXofeSomF50xPnn+enPc9OYy07KN07HyyPIrif9BNK16oiJBaVLLu6zE065K+JWUv"
    "7QgYuO6WqwpyGvZjdz12TeSpTY9cyHoPbVr3Ad88iT23Arq27YgyKFWzqoiiK5GyKUS+2DZw"
    "rOC2G1L0IktZFOScVH+URBIPLEpNVuS7N7ENz8YW8b96Lgb5MxFiSeyHvq7Xfsrb8Nl73LHq"
    "labLHppR5Z62PWsoqNgCWyoKWFPXdj+o6zgnjxxCNunQJWZ01YOGQ9NmJ95n1rRDjaDlQCyZ"
    "CCVi+1rBb784Bcqj5SBoa2Z2UhNN7eDI3qlQHnuOgr7amVBNP6CWFQ/I3jDNXDJM4wyat2Re"
    "TqKQTbVgynyWomSgbVfFH01lZU09FbvaBkrDpqqO84rZPKNlLICO6tDOeXviM42fd+b4Cx0p"
    "gqm0gb9SAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDE2LTA5LTE3VDE1OjIwOjMxKzA4OjAwmZRk"
    "uAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxNC0wNS0wMVQyMTowOTo1MCswODowMIreeDEAAABN"
    "dEVYdHNvZnR3YXJlAEltYWdlTWFnaWNrIDcuMC4xLTYgUTE2IHg4Nl82NCAyMDE2LTA5LTE3"
    "IGh0dHA6Ly93d3cuaW1hZ2VtYWdpY2sub3Jn3dmlTgAAACV0RVh0c3ZnOmNvbW1lbnQAIEdl"
    "bmVyYXRlZCBieSBJY29Nb29uLmlvIDDLy0gAAAAYdEVYdFRodW1iOjpEb2N1bWVudDo6UGFn"
    "ZXMAMaf/uy8AAAAYdEVYdFRodW1iOjpJbWFnZTo6SGVpZ2h0ADcxMRUA1lUAAAAXdEVYdFRo"
    "dW1iOjpJbWFnZTo6V2lkdGgANTM2KSelRwAAABl0RVh0VGh1bWI6Ok1pbWV0eXBlAGltYWdl"
    "L3BuZz+yVk4AAAAXdEVYdFRodW1iOjpNVGltZQAxMzk4OTQ5NzkwHzJ6LgAAABJ0RVh0VGh1"
    "bWI6OlNpemUAMTEuNktCicMHqgAAAF90RVh0VGh1bWI6OlVSSQBmaWxlOi8vL2hvbWUvd3d3"
    "cm9vdC9zaXRlL3d3dy5lYXN5aWNvbi5uZXQvY2RuLWltZy5lYXN5aWNvbi5jbi9zcmMvMTE1"
    "ODEvMTE1ODE0OC5wbmeDRBaAAAAAAElFTkSuQmCC")
index.append('remove')
catalog['remove'] = remove

#----------------------------------------------------------------------
save = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAE3UlEQVR42rWVa2wUVRTHz53Z"
    "97MvRExq5KNpNDHRBBM1bdNiC7VQEBHxgegHSJRHWyulLTNLH0Zogoii1je+kWobkRaQWtm2"
    "tIB9kfhdvlATQ9vthrqP2es5985ud4v96GTP3Htn7pzfOf977l0G//PF6FZbU3OvoqhPxWJR"
    "8PmzoLB0Dfi9PlBVBWcw/ElTFIWGABx/PCEMb8ATCQiFw3C+92eYnZ4G1aJCdnb29w2NjX8I"
    "wM4dO7Spqb80m83G8vPvhl2vN3G3w87MIDgzA5EgHAse44psAVseno+wN5s1mAuFOE31+/36"
    "ofbDAfHhy9tf0sLhsEYRrlhxF1Q36DB3K3p7qmyhz8wH1BIky2OHVq2RAGKOx+MJHDn6lgRs"
    "3/aiho0myFlZsE9r4VluRyoD6SkF4dInS2WGIvGZ8D+s5UADhGZnOb10u9362+8ck4Btz7+Q"
    "AWg82MZzvM5MgNkh0VF2xrlsE3hD46FbEfaGJgE03+1x6+8ePy4Bz219VkMoAYAA+wNtiyTi"
    "pnNzgZNPxGLLvtdlg0OBRgKIaZhB4L0P3peArVueERlQan6sojq9lXuctswM+NIZUG8+Gmft"
    "BwkwIyRyuVx6x0cfSsCWzU9nSFR7oJU7bdYMAE9mIn4ENAHms2jcYEeaFyQiwMeffiIBm5/c"
    "pIEpkc/vh+qmNgjNR4GldM/s8DSpTKiQ6GhLQ6qKnE5n4LMTn0vApg0bZQaYms/nh91NrSJN"
    "tuCHpelPHpmQn6QyM6A5x1obIBzCDPBTBOgnvvxCAjasr9KYlAgsVisUV2zEXayCBY1asYPF"
    "rlIEJ5FICO8GtkbcgLgRh4RhQN/pThzHxRwHZvDVN19LwPrKdak1SNedLSrTRWWbXr588bcO"
    "h0P/9uR3ElC5tiIlUbJQ/rOfPl5qjtl32O36yc5TElBRvub2DHCSIg84jjIxKZM47Ehxs0w5"
    "I5lQHjzvEoykS2ZgR0Bn148SUL768SQAkofanppqyMvLEwEtddG7zlOd0N/XJ9YDD0vwejzi"
    "HfYD3ad/koDSouJkmYqx1Wrlu/buYTPTM3D9+p8iuvz8fLhn5UrhVxxEeBmGwS6c/wUGgkGO"
    "ABbHBXY6HCID9KGfOdsrAYWPPpYhEdJ5zWu1bHBwEM71nuX4ISsuKYHKdZVif9EYTbS/9ffD"
    "yPAIR5lYLBYT35IfGwLO9V2QgEdWPZzaaKJUsTTr9tfDEAJ6z/QARgrFpSVQVlYGFCUZPaMW"
    "o4ffr1wVpUtj1B4sFgv9CQV+DV6UgFUPPpSZgd3O6+r3sYGLQejt6RFSFBYXQUlpKTkRY4yW"
    "o7FLg0MwPjaWWmQsz+Qm1YOXhiTggfvur1ZUtT0JwBLju6v3smBwALq7u0S1lJWVQ2FRIZBj"
    "kgYhAjAyPAzXJiYQwEWdWlEirD6C6VfHxyTA5XS5li9b9oPP611tniOw89VXRCt2LMoRiUSE"
    "pctDEV+5fBmujU8IaamUSR66/r558/CNqRv1ybq3oRXdecfyZlwcb05OjrK28gnc7U6abcGA"
    "VHSq0nEQx8jxmUFrjeP45ORkdGJ8PEJZyv9psVdi07OzHaG5uY70I8CNlo2mFhQUWKuqqty5"
    "ubkqLpqKJaeQA4yYm/uC1sEIhUKx0dHR+a6urghmpKT5MtBm0ML/ArBlxEPZ/ksHAAAAAElF"
    "TkSuQmCC")
index.append('save')
catalog['save'] = save

#----------------------------------------------------------------------
segment = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAADLklEQVRIS62WX0hTURzHv7+7"
    "KWrz/5/8hxkWzchaLz1Eha3c5kvpQ+RDYYEzoofoIQz6o9lTRKkvlluUEdGLkFDgtkgjMQok"
    "TWxRKM7IpbSWzmvTeXdPXPWWyf6Yet4O95zv55zv73vuOYQ1ajZTkQZQNIPDRsbYPb3Rek6S"
    "pmD6bbcNuQoFO0xECYvHiASHvsLyYOk8m9ngUCqVGxLT1uO7cwSMxFJ9ha01KECaAGBDwAUw"
    "NOsqLScXf7OZDSw1Mxt5+QV486INBHauyGitXxlAUl4CsZn09SA6u2ALLwgoKD5tcQQHmIo0"
    "RFyhiMUWMQ2BDksi0eMqpA5l9aobG3bKO7He1ZVwjHIFgVol8ZA1CFYbq9nQnDaYXZ7Vv3lu"
    "iCfVPbDp/vX5ToBGD9u62XKDFO3xYlu7HUkj44jMTUNkZjL41x/hznGOqhsbMgIC2t5+fLkc"
    "QHLvl5Qca7+aY0wRu2crotTZED2/4G7pApsRkPasKqDdQWsgQ0/U1CXsdvo7Spx+TURGohCn"
    "3a7k4mLgGxqDp/09mM+P0S1D2H7zTmBAKItmBQEfunsw6ZvG0dlYaPfvmuPyXXZ4+4YxHT+F"
    "YY0d3gQeOqMlMCCURXb7QPanzwN5SoUCsYoIXNpcgFlbn19wTyoA1tBzqOMs0bwuA67+tVp0"
    "6o02U9gUVV6oqwGhOiU9Ha7RUWi/M6Yd801xoOMpT6tapcMVrH4M4hG90dYSMkU8z6PnXQ/i"
    "EpPgm5mG38ujdGh6x8HHF/skYavZMENAZCDIH0C4FHV2vt3m+vEzWd6FKmKy41btFe0cwKQr"
    "BnFVDKyfQC4ZRCK+6U5ZmsJaJA2QUqSa9X0VKWZdlCoG/IQH8dHufTeuXOtcTrzDxlQSOV97"
    "ee+EN+mVLBgf4XHdqK1OXRXA2qRTg+PKZJFBT9YBnxC9R+6nq0aOlZ158igcJMTfVG8HKP9f"
    "ASk0C7FkcOgrLRvXDsDYgvafNQ3rjJbcFQP+sYiJ6URUDlDU/KliE4BYqKt83rtigDxx7q4l"
    "rgPyvfAf4mFjulrxsACr2VBDQPX/2rLYtpDnYP4pwi3cF8vzfGlNfgNUVFsojJ6IigAAAABJ"
    "RU5ErkJggg==")
index.append('segment')
catalog['segment'] = segment

#----------------------------------------------------------------------
upload = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAyUlEQVR42mNkoDFgHBYWfABi"
    "HhqZ/wVkwR8gZgfi/zRw/E+YBaxQC44DsSUSfRSIrcm0gAmIf6FbQE2AYgEHEP+jgQU/GKEG"
    "U9twuCV0CyJiLeAC4lggXgDEP6ltgTwQrwdiAyA+BcTBQPyUWhaYAfEGIO4A4j4grgXiLCD2"
    "BuJL1LDACIi5gfgwVD0bEDsA8SsgvkLNOGBAsoBQyhvBFiQD8Vwi1NG3LGInwsvkWPATucIB"
    "+YARySfY2MhiDATUg8CX4VEn0xQAAHqXULulLZ8OAAAAAElFTkSuQmCC")
index.append('upload')
catalog['upload'] = upload

